-- MySQL Script generated by MySQL Workbench
-- dom 01 dic 2019 22:29:36 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuarios` (
  `idTipoUsuario` INT NOT NULL,
  `DescripcionTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Edad` INT(11) NOT NULL,
  `TipoUsuario_idTipoUsuario` INT NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NombreUsuario`),
  INDEX `fk_Usuario_TipoUsuario_idx` (`TipoUsuario_idTipoUsuario` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario`
    FOREIGN KEY (`TipoUsuario_idTipoUsuario`)
    REFERENCES `mydb`.`TipoUsuarios` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamentos` (
  `idDepartamentos` INT NOT NULL,
  `DescripcionDepartamentos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `NumeroComentario` INT NOT NULL,
  `DescripcionComentario` VARCHAR(500) NOT NULL,
  `FechaCreacion` VARCHAR(45) NOT NULL,
  `Usuarios_NombreUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NumeroComentario`),
  INDEX `fk_Comentarios_Usuarios1_idx` (`Usuarios_NombreUsuario` ASC),
  CONSTRAINT `fk_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_NombreUsuario`)
    REFERENCES `mydb`.`Usuarios` (`NombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reportes` (
  `idReportes` INT NOT NULL,
  `NombreReporte` VARCHAR(60) NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  `FechaElaboracion` VARCHAR(45) NOT NULL,
  `Departamentos_idDepartamentos` INT NOT NULL,
  `Comentarios_NumeroComentario` INT NOT NULL,
  PRIMARY KEY (`idReportes`),
  INDEX `fk_Reportes_Departamentos1_idx` (`Departamentos_idDepartamentos` ASC),
  INDEX `fk_Reportes_Comentarios1_idx` (`Comentarios_NumeroComentario` ASC),
  CONSTRAINT `fk_Reportes_Departamentos1`
    FOREIGN KEY (`Departamentos_idDepartamentos`)
    REFERENCES `mydb`.`Departamentos` (`idDepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Comentarios1`
    FOREIGN KEY (`Comentarios_NumeroComentario`)
    REFERENCES `mydb`.`Comentarios` (`NumeroComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  `Reportes_idReportes` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Reportes1_idx` (`Reportes_idReportes` ASC),
  CONSTRAINT `fk_Clientes_Reportes1`
    FOREIGN KEY (`Reportes_idReportes`)
    REFERENCES `mydb`.`Reportes` (`idReportes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
